name: Build and deploy ASP.Net Core app to Azure Web App - backend-tx-ecm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Zip artifact
        run: Compress-Archive -Path "${{env.DOTNET_ROOT}}/myapp" -DestinationPath "${{env.DOTNET_ROOT}}/myapp.zip"

      - name: Upload artifact to JFrog Artifactory
        run: |
          curl -X PUT \
               -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }} \
               -T "${{env.DOTNET_ROOT}}/myapp.zip" \
               "${{ secrets.JFROG_URL }}/artifactory/${{ secrets.JFROG_REPO }}/backend-tx-ecm/myapp.zip"
        shell: bash
        env:
          DOTNET_ROOT: ${{ env.DOTNET_ROOT }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from JFrog
        run: |
          curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }} \
               -o myapp.zip \
               "${{ secrets.JFROG_URL }}/artifactory/${{ secrets.JFROG_REPO }}/backend-tx-ecm/myapp.zip"
        shell: bash

      - name: Extract artifact
        run: Expand-Archive -Path myapp.zip -DestinationPath myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A78054C17AE34C3BB6E9964842A2EFBA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E28CB2EFBFE74F8090231456BEE5918C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1675C2A7B03A4853BDCE6F0AB62DC05E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-tx-ecm'
          slot-name: Production
          package: myapp
