name: Build and deploy ASP.Net Core app to Azure Web App - backend-tx-ecm

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish -c Release -o myapp
          ls -R myapp

      - name: Zip artifact
        run: Compress-Archive -Path myapp -DestinationPath myapp.zip

      - name: Verify zip creation
        run: Expand-Archive -Path myapp.zip -DestinationPath myapp_verify -Force

      - name: Upload artifact to JFrog Artifactory
        run: |
          curl -f -L -X PUT \
               -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }} \
               -T myapp.zip \
               "${{ secrets.JFROG_URL }}/artifactory/${{ secrets.JFROG_REPO }}/backend-tx-ecm/myapp.zip"
        shell: bash
        env:
          DOTNET_ROOT: ${{ env.DOTNET_ROOT }}


  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from JFrog
        run: |
          # curl -f -L -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }} \
          #      -o myapp.zip \
          #      "${{ secrets.JFROG_URL }}/artifactory/${{ secrets.JFROG_REPO }}/backend-tx-ecm/myapp.zip"
          curl -u s.gurpreet@testingxperts.com:${{ secrets.JFROG_API_KEY }} -L -O "https://trialee1qxw.jfrog.io/artifactory/txecom-be-generic-local/backend-tx-ecm/myapp.zip"
        shell: bash

      - name: Debug artifact
        run: |
          ls -l myapp.zip
          unzip -t myapp.zip || cat myapp.zip
        shell: bash

      - name: Extract artifact
        run: unzip -o myapp.zip -d myapp
        shell: bash

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A78054C17AE34C3BB6E9964842A2EFBA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E28CB2EFBFE74F8090231456BEE5918C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1675C2A7B03A4853BDCE6F0AB62DC05E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-tx-ecm'
          slot-name: Production
          package: myapp
